services:
  tg-spam:
    build:
      context: .
    image: tg-spam-local:ua
    container_name: tg-spam
    hostname: tg-spam
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./var/tg-spam:/srv/data
      - ./logs:/srv/logs
    ports:
      - "127.0.0.1:8080:8080"

  cloudflared-tgadmin:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tgadmin
    restart: unless-stopped
    depends_on:
      - tg-spam
    env_file:
      - .env.tg-spam.local
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TOKEN}
