site_name: Shield
site_url: https://redstone-md.github.io/shield/
site_author: Redstone MD
site_description: >-
  Shield is a self-hosted anti-spam bot for Telegram groups.

repo_name: redstone-md/shield
repo_url: https://github.com/redstone-md/shield
copyright: Some rights reserved &copy; 2026 Redstone MD

theme:
  name: material
  custom_dir: overrides
  favicon: favicon.png
  language: en
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - navigation.sections
  logo: icon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/redstone-md/shield
    - icon: fontawesome/brands/docker
      link: https://github.com/redstone-md/shield/pkgs/container/shield

markdown_extensions:
  - smarty
  - sane_lists
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Shield: index.md
