// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/redstone-md/shield/app/storage"
	"github.com/redstone-md/shield/lib/spamcheck"
	"sync"
)

// LocatorMock is a mock implementation of events.Locator.
//
//	func TestSomethingThatUsesLocator(t *testing.T) {
//
//		// make and configure a mocked events.Locator
//		mockedLocator := &LocatorMock{
//			AddMessageFunc: func(ctx context.Context, msg string, chatID int64, userID int64, userName string, msgID int) error {
//				panic("mock out the AddMessage method")
//			},
//			AddSpamFunc: func(ctx context.Context, userID int64, checks []spamcheck.Response) error {
//				panic("mock out the AddSpam method")
//			},
//			GetUserDCFunc: func(ctx context.Context, userID int64) (int, bool) {
//				panic("mock out the GetUserDC method")
//			},
//			GetUserMessagesFunc: func(ctx context.Context, userID int64, limit int) ([]storage.UserMessage, error) {
//				panic("mock out the GetUserMessages method")
//			},
//			MessageFunc: func(ctx context.Context, msg string) (storage.MsgMeta, bool) {
//				panic("mock out the Message method")
//			},
//			MsgHashFunc: func(msg string) string {
//				panic("mock out the MsgHash method")
//			},
//			SetUserDCFunc: func(ctx context.Context, userID int64, dc int) error {
//				panic("mock out the SetUserDC method")
//			},
//			SpamFunc: func(ctx context.Context, userID int64) (storage.SpamData, bool) {
//				panic("mock out the Spam method")
//			},
//			UserIDByNameFunc: func(ctx context.Context, userName string) int64 {
//				panic("mock out the UserIDByName method")
//			},
//			UserNameByIDFunc: func(ctx context.Context, userID int64) string {
//				panic("mock out the UserNameByID method")
//			},
//		}
//
//		// use mockedLocator in code that requires events.Locator
//		// and then make assertions.
//
//	}
type LocatorMock struct {
	// AddMessageFunc mocks the AddMessage method.
	AddMessageFunc func(ctx context.Context, msg string, chatID int64, userID int64, userName string, msgID int) error

	// AddSpamFunc mocks the AddSpam method.
	AddSpamFunc func(ctx context.Context, userID int64, checks []spamcheck.Response) error

	// GetUserDCFunc mocks the GetUserDC method.
	GetUserDCFunc func(ctx context.Context, userID int64) (int, bool)

	// GetUserMessagesFunc mocks the GetUserMessages method.
	GetUserMessagesFunc func(ctx context.Context, userID int64, limit int) ([]storage.UserMessage, error)

	// MessageFunc mocks the Message method.
	MessageFunc func(ctx context.Context, msg string) (storage.MsgMeta, bool)

	// MsgHashFunc mocks the MsgHash method.
	MsgHashFunc func(msg string) string

	// SetUserDCFunc mocks the SetUserDC method.
	SetUserDCFunc func(ctx context.Context, userID int64, dc int) error

	// SpamFunc mocks the Spam method.
	SpamFunc func(ctx context.Context, userID int64) (storage.SpamData, bool)

	// UserIDByNameFunc mocks the UserIDByName method.
	UserIDByNameFunc func(ctx context.Context, userName string) int64

	// UserNameByIDFunc mocks the UserNameByID method.
	UserNameByIDFunc func(ctx context.Context, userID int64) string

	// calls tracks calls to the methods.
	calls struct {
		// AddMessage holds details about calls to the AddMessage method.
		AddMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// ChatID is the chatID argument value.
			ChatID int64
			// UserID is the userID argument value.
			UserID int64
			// UserName is the userName argument value.
			UserName string
			// MsgID is the msgID argument value.
			MsgID int
		}
		// AddSpam holds details about calls to the AddSpam method.
		AddSpam []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// Checks is the checks argument value.
			Checks []spamcheck.Response
		}
		// GetUserDC holds details about calls to the GetUserDC method.
		GetUserDC []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// GetUserMessages holds details about calls to the GetUserMessages method.
		GetUserMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// Limit is the limit argument value.
			Limit int
		}
		// Message holds details about calls to the Message method.
		Message []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
		}
		// MsgHash holds details about calls to the MsgHash method.
		MsgHash []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// SetUserDC holds details about calls to the SetUserDC method.
		SetUserDC []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// Dc is the dc argument value.
			Dc int
		}
		// Spam holds details about calls to the Spam method.
		Spam []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// UserIDByName holds details about calls to the UserIDByName method.
		UserIDByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserName is the userName argument value.
			UserName string
		}
		// UserNameByID holds details about calls to the UserNameByID method.
		UserNameByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
	}
	lockAddMessage      sync.RWMutex
	lockAddSpam         sync.RWMutex
	lockGetUserDC       sync.RWMutex
	lockGetUserMessages sync.RWMutex
	lockMessage         sync.RWMutex
	lockMsgHash         sync.RWMutex
	lockSetUserDC       sync.RWMutex
	lockSpam            sync.RWMutex
	lockUserIDByName    sync.RWMutex
	lockUserNameByID    sync.RWMutex
}

// AddMessage calls AddMessageFunc.
func (mock *LocatorMock) AddMessage(ctx context.Context, msg string, chatID int64, userID int64, userName string, msgID int) error {
	if mock.AddMessageFunc == nil {
		panic("LocatorMock.AddMessageFunc: method is nil but Locator.AddMessage was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Msg      string
		ChatID   int64
		UserID   int64
		UserName string
		MsgID    int
	}{
		Ctx:      ctx,
		Msg:      msg,
		ChatID:   chatID,
		UserID:   userID,
		UserName: userName,
		MsgID:    msgID,
	}
	mock.lockAddMessage.Lock()
	mock.calls.AddMessage = append(mock.calls.AddMessage, callInfo)
	mock.lockAddMessage.Unlock()
	return mock.AddMessageFunc(ctx, msg, chatID, userID, userName, msgID)
}

// AddMessageCalls gets all the calls that were made to AddMessage.
// Check the length with:
//
//	len(mockedLocator.AddMessageCalls())
func (mock *LocatorMock) AddMessageCalls() []struct {
	Ctx      context.Context
	Msg      string
	ChatID   int64
	UserID   int64
	UserName string
	MsgID    int
} {
	var calls []struct {
		Ctx      context.Context
		Msg      string
		ChatID   int64
		UserID   int64
		UserName string
		MsgID    int
	}
	mock.lockAddMessage.RLock()
	calls = mock.calls.AddMessage
	mock.lockAddMessage.RUnlock()
	return calls
}

// ResetAddMessageCalls reset all the calls that were made to AddMessage.
func (mock *LocatorMock) ResetAddMessageCalls() {
	mock.lockAddMessage.Lock()
	mock.calls.AddMessage = nil
	mock.lockAddMessage.Unlock()
}

// AddSpam calls AddSpamFunc.
func (mock *LocatorMock) AddSpam(ctx context.Context, userID int64, checks []spamcheck.Response) error {
	if mock.AddSpamFunc == nil {
		panic("LocatorMock.AddSpamFunc: method is nil but Locator.AddSpam was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		Checks []spamcheck.Response
	}{
		Ctx:    ctx,
		UserID: userID,
		Checks: checks,
	}
	mock.lockAddSpam.Lock()
	mock.calls.AddSpam = append(mock.calls.AddSpam, callInfo)
	mock.lockAddSpam.Unlock()
	return mock.AddSpamFunc(ctx, userID, checks)
}

// AddSpamCalls gets all the calls that were made to AddSpam.
// Check the length with:
//
//	len(mockedLocator.AddSpamCalls())
func (mock *LocatorMock) AddSpamCalls() []struct {
	Ctx    context.Context
	UserID int64
	Checks []spamcheck.Response
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		Checks []spamcheck.Response
	}
	mock.lockAddSpam.RLock()
	calls = mock.calls.AddSpam
	mock.lockAddSpam.RUnlock()
	return calls
}

// ResetAddSpamCalls reset all the calls that were made to AddSpam.
func (mock *LocatorMock) ResetAddSpamCalls() {
	mock.lockAddSpam.Lock()
	mock.calls.AddSpam = nil
	mock.lockAddSpam.Unlock()
}

// GetUserDC calls GetUserDCFunc.
func (mock *LocatorMock) GetUserDC(ctx context.Context, userID int64) (int, bool) {
	if mock.GetUserDCFunc == nil {
		panic("LocatorMock.GetUserDCFunc: method is nil but Locator.GetUserDC was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUserDC.Lock()
	mock.calls.GetUserDC = append(mock.calls.GetUserDC, callInfo)
	mock.lockGetUserDC.Unlock()
	return mock.GetUserDCFunc(ctx, userID)
}

// GetUserDCCalls gets all the calls that were made to GetUserDC.
// Check the length with:
//
//	len(mockedLocator.GetUserDCCalls())
func (mock *LocatorMock) GetUserDCCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockGetUserDC.RLock()
	calls = mock.calls.GetUserDC
	mock.lockGetUserDC.RUnlock()
	return calls
}

// ResetGetUserDCCalls reset all the calls that were made to GetUserDC.
func (mock *LocatorMock) ResetGetUserDCCalls() {
	mock.lockGetUserDC.Lock()
	mock.calls.GetUserDC = nil
	mock.lockGetUserDC.Unlock()
}

// GetUserMessages calls GetUserMessagesFunc.
func (mock *LocatorMock) GetUserMessages(ctx context.Context, userID int64, limit int) ([]storage.UserMessage, error) {
	if mock.GetUserMessagesFunc == nil {
		panic("LocatorMock.GetUserMessagesFunc: method is nil but Locator.GetUserMessages was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		Limit  int
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
	}
	mock.lockGetUserMessages.Lock()
	mock.calls.GetUserMessages = append(mock.calls.GetUserMessages, callInfo)
	mock.lockGetUserMessages.Unlock()
	return mock.GetUserMessagesFunc(ctx, userID, limit)
}

// GetUserMessagesCalls gets all the calls that were made to GetUserMessages.
// Check the length with:
//
//	len(mockedLocator.GetUserMessagesCalls())
func (mock *LocatorMock) GetUserMessagesCalls() []struct {
	Ctx    context.Context
	UserID int64
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		Limit  int
	}
	mock.lockGetUserMessages.RLock()
	calls = mock.calls.GetUserMessages
	mock.lockGetUserMessages.RUnlock()
	return calls
}

// ResetGetUserMessagesCalls reset all the calls that were made to GetUserMessages.
func (mock *LocatorMock) ResetGetUserMessagesCalls() {
	mock.lockGetUserMessages.Lock()
	mock.calls.GetUserMessages = nil
	mock.lockGetUserMessages.Unlock()
}

// Message calls MessageFunc.
func (mock *LocatorMock) Message(ctx context.Context, msg string) (storage.MsgMeta, bool) {
	if mock.MessageFunc == nil {
		panic("LocatorMock.MessageFunc: method is nil but Locator.Message was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockMessage.Lock()
	mock.calls.Message = append(mock.calls.Message, callInfo)
	mock.lockMessage.Unlock()
	return mock.MessageFunc(ctx, msg)
}

// MessageCalls gets all the calls that were made to Message.
// Check the length with:
//
//	len(mockedLocator.MessageCalls())
func (mock *LocatorMock) MessageCalls() []struct {
	Ctx context.Context
	Msg string
} {
	var calls []struct {
		Ctx context.Context
		Msg string
	}
	mock.lockMessage.RLock()
	calls = mock.calls.Message
	mock.lockMessage.RUnlock()
	return calls
}

// ResetMessageCalls reset all the calls that were made to Message.
func (mock *LocatorMock) ResetMessageCalls() {
	mock.lockMessage.Lock()
	mock.calls.Message = nil
	mock.lockMessage.Unlock()
}

// MsgHash calls MsgHashFunc.
func (mock *LocatorMock) MsgHash(msg string) string {
	if mock.MsgHashFunc == nil {
		panic("LocatorMock.MsgHashFunc: method is nil but Locator.MsgHash was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockMsgHash.Lock()
	mock.calls.MsgHash = append(mock.calls.MsgHash, callInfo)
	mock.lockMsgHash.Unlock()
	return mock.MsgHashFunc(msg)
}

// MsgHashCalls gets all the calls that were made to MsgHash.
// Check the length with:
//
//	len(mockedLocator.MsgHashCalls())
func (mock *LocatorMock) MsgHashCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockMsgHash.RLock()
	calls = mock.calls.MsgHash
	mock.lockMsgHash.RUnlock()
	return calls
}

// ResetMsgHashCalls reset all the calls that were made to MsgHash.
func (mock *LocatorMock) ResetMsgHashCalls() {
	mock.lockMsgHash.Lock()
	mock.calls.MsgHash = nil
	mock.lockMsgHash.Unlock()
}

// SetUserDC calls SetUserDCFunc.
func (mock *LocatorMock) SetUserDC(ctx context.Context, userID int64, dc int) error {
	if mock.SetUserDCFunc == nil {
		panic("LocatorMock.SetUserDCFunc: method is nil but Locator.SetUserDC was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		Dc     int
	}{
		Ctx:    ctx,
		UserID: userID,
		Dc:     dc,
	}
	mock.lockSetUserDC.Lock()
	mock.calls.SetUserDC = append(mock.calls.SetUserDC, callInfo)
	mock.lockSetUserDC.Unlock()
	return mock.SetUserDCFunc(ctx, userID, dc)
}

// SetUserDCCalls gets all the calls that were made to SetUserDC.
// Check the length with:
//
//	len(mockedLocator.SetUserDCCalls())
func (mock *LocatorMock) SetUserDCCalls() []struct {
	Ctx    context.Context
	UserID int64
	Dc     int
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		Dc     int
	}
	mock.lockSetUserDC.RLock()
	calls = mock.calls.SetUserDC
	mock.lockSetUserDC.RUnlock()
	return calls
}

// ResetSetUserDCCalls reset all the calls that were made to SetUserDC.
func (mock *LocatorMock) ResetSetUserDCCalls() {
	mock.lockSetUserDC.Lock()
	mock.calls.SetUserDC = nil
	mock.lockSetUserDC.Unlock()
}

// Spam calls SpamFunc.
func (mock *LocatorMock) Spam(ctx context.Context, userID int64) (storage.SpamData, bool) {
	if mock.SpamFunc == nil {
		panic("LocatorMock.SpamFunc: method is nil but Locator.Spam was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockSpam.Lock()
	mock.calls.Spam = append(mock.calls.Spam, callInfo)
	mock.lockSpam.Unlock()
	return mock.SpamFunc(ctx, userID)
}

// SpamCalls gets all the calls that were made to Spam.
// Check the length with:
//
//	len(mockedLocator.SpamCalls())
func (mock *LocatorMock) SpamCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockSpam.RLock()
	calls = mock.calls.Spam
	mock.lockSpam.RUnlock()
	return calls
}

// ResetSpamCalls reset all the calls that were made to Spam.
func (mock *LocatorMock) ResetSpamCalls() {
	mock.lockSpam.Lock()
	mock.calls.Spam = nil
	mock.lockSpam.Unlock()
}

// UserIDByName calls UserIDByNameFunc.
func (mock *LocatorMock) UserIDByName(ctx context.Context, userName string) int64 {
	if mock.UserIDByNameFunc == nil {
		panic("LocatorMock.UserIDByNameFunc: method is nil but Locator.UserIDByName was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserName string
	}{
		Ctx:      ctx,
		UserName: userName,
	}
	mock.lockUserIDByName.Lock()
	mock.calls.UserIDByName = append(mock.calls.UserIDByName, callInfo)
	mock.lockUserIDByName.Unlock()
	return mock.UserIDByNameFunc(ctx, userName)
}

// UserIDByNameCalls gets all the calls that were made to UserIDByName.
// Check the length with:
//
//	len(mockedLocator.UserIDByNameCalls())
func (mock *LocatorMock) UserIDByNameCalls() []struct {
	Ctx      context.Context
	UserName string
} {
	var calls []struct {
		Ctx      context.Context
		UserName string
	}
	mock.lockUserIDByName.RLock()
	calls = mock.calls.UserIDByName
	mock.lockUserIDByName.RUnlock()
	return calls
}

// ResetUserIDByNameCalls reset all the calls that were made to UserIDByName.
func (mock *LocatorMock) ResetUserIDByNameCalls() {
	mock.lockUserIDByName.Lock()
	mock.calls.UserIDByName = nil
	mock.lockUserIDByName.Unlock()
}

// UserNameByID calls UserNameByIDFunc.
func (mock *LocatorMock) UserNameByID(ctx context.Context, userID int64) string {
	if mock.UserNameByIDFunc == nil {
		panic("LocatorMock.UserNameByIDFunc: method is nil but Locator.UserNameByID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockUserNameByID.Lock()
	mock.calls.UserNameByID = append(mock.calls.UserNameByID, callInfo)
	mock.lockUserNameByID.Unlock()
	return mock.UserNameByIDFunc(ctx, userID)
}

// UserNameByIDCalls gets all the calls that were made to UserNameByID.
// Check the length with:
//
//	len(mockedLocator.UserNameByIDCalls())
func (mock *LocatorMock) UserNameByIDCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockUserNameByID.RLock()
	calls = mock.calls.UserNameByID
	mock.lockUserNameByID.RUnlock()
	return calls
}

// ResetUserNameByIDCalls reset all the calls that were made to UserNameByID.
func (mock *LocatorMock) ResetUserNameByIDCalls() {
	mock.lockUserNameByID.Lock()
	mock.calls.UserNameByID = nil
	mock.lockUserNameByID.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *LocatorMock) ResetCalls() {
	mock.lockAddMessage.Lock()
	mock.calls.AddMessage = nil
	mock.lockAddMessage.Unlock()

	mock.lockAddSpam.Lock()
	mock.calls.AddSpam = nil
	mock.lockAddSpam.Unlock()

	mock.lockGetUserDC.Lock()
	mock.calls.GetUserDC = nil
	mock.lockGetUserDC.Unlock()

	mock.lockGetUserMessages.Lock()
	mock.calls.GetUserMessages = nil
	mock.lockGetUserMessages.Unlock()

	mock.lockMessage.Lock()
	mock.calls.Message = nil
	mock.lockMessage.Unlock()

	mock.lockMsgHash.Lock()
	mock.calls.MsgHash = nil
	mock.lockMsgHash.Unlock()

	mock.lockSetUserDC.Lock()
	mock.calls.SetUserDC = nil
	mock.lockSetUserDC.Unlock()

	mock.lockSpam.Lock()
	mock.calls.Spam = nil
	mock.lockSpam.Unlock()

	mock.lockUserIDByName.Lock()
	mock.calls.UserIDByName = nil
	mock.lockUserIDByName.Unlock()

	mock.lockUserNameByID.Lock()
	mock.calls.UserNameByID = nil
	mock.lockUserNameByID.Unlock()
}
