// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/umputun/tg-spam/lib/approved"
	"sync"
)

// ApprovedUsersMock is a mock implementation of bot.ApprovedUsers.
//
//	func TestSomethingThatUsesApprovedUsers(t *testing.T) {
//
//		// make and configure a mocked bot.ApprovedUsers
//		mockedApprovedUsers := &ApprovedUsersMock{
//			AddApprovedUserFunc: func(user approved.UserInfo) error {
//				panic("mock out the AddApprovedUser method")
//			},
//			ApprovedUsersFunc: func() []approved.UserInfo {
//				panic("mock out the ApprovedUsers method")
//			},
//			IsApprovedUserFunc: func(userID string) bool {
//				panic("mock out the IsApprovedUser method")
//			},
//			RemoveApprovedUserFunc: func(id string) error {
//				panic("mock out the RemoveApprovedUser method")
//			},
//		}
//
//		// use mockedApprovedUsers in code that requires bot.ApprovedUsers
//		// and then make assertions.
//
//	}
type ApprovedUsersMock struct {
	// AddApprovedUserFunc mocks the AddApprovedUser method.
	AddApprovedUserFunc func(user approved.UserInfo) error

	// ApprovedUsersFunc mocks the ApprovedUsers method.
	ApprovedUsersFunc func() []approved.UserInfo

	// IsApprovedUserFunc mocks the IsApprovedUser method.
	IsApprovedUserFunc func(userID string) bool

	// RemoveApprovedUserFunc mocks the RemoveApprovedUser method.
	RemoveApprovedUserFunc func(id string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddApprovedUser holds details about calls to the AddApprovedUser method.
		AddApprovedUser []struct {
			// User is the user argument value.
			User approved.UserInfo
		}
		// ApprovedUsers holds details about calls to the ApprovedUsers method.
		ApprovedUsers []struct {
		}
		// IsApprovedUser holds details about calls to the IsApprovedUser method.
		IsApprovedUser []struct {
			// UserID is the userID argument value.
			UserID string
		}
		// RemoveApprovedUser holds details about calls to the RemoveApprovedUser method.
		RemoveApprovedUser []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockAddApprovedUser    sync.RWMutex
	lockApprovedUsers      sync.RWMutex
	lockIsApprovedUser     sync.RWMutex
	lockRemoveApprovedUser sync.RWMutex
}

// AddApprovedUser calls AddApprovedUserFunc.
func (mock *ApprovedUsersMock) AddApprovedUser(user approved.UserInfo) error {
	if mock.AddApprovedUserFunc == nil {
		panic("ApprovedUsersMock.AddApprovedUserFunc: method is nil but ApprovedUsers.AddApprovedUser was just called")
	}
	callInfo := struct {
		User approved.UserInfo
	}{
		User: user,
	}
	mock.lockAddApprovedUser.Lock()
	mock.calls.AddApprovedUser = append(mock.calls.AddApprovedUser, callInfo)
	mock.lockAddApprovedUser.Unlock()
	return mock.AddApprovedUserFunc(user)
}

// AddApprovedUserCalls gets all the calls that were made to AddApprovedUser.
// Check the length with:
//
//	len(mockedApprovedUsers.AddApprovedUserCalls())
func (mock *ApprovedUsersMock) AddApprovedUserCalls() []struct {
	User approved.UserInfo
} {
	var calls []struct {
		User approved.UserInfo
	}
	mock.lockAddApprovedUser.RLock()
	calls = mock.calls.AddApprovedUser
	mock.lockAddApprovedUser.RUnlock()
	return calls
}

// ResetAddApprovedUserCalls reset all the calls that were made to AddApprovedUser.
func (mock *ApprovedUsersMock) ResetAddApprovedUserCalls() {
	mock.lockAddApprovedUser.Lock()
	mock.calls.AddApprovedUser = nil
	mock.lockAddApprovedUser.Unlock()
}

// ApprovedUsers calls ApprovedUsersFunc.
func (mock *ApprovedUsersMock) ApprovedUsers() []approved.UserInfo {
	if mock.ApprovedUsersFunc == nil {
		panic("ApprovedUsersMock.ApprovedUsersFunc: method is nil but ApprovedUsers.ApprovedUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = append(mock.calls.ApprovedUsers, callInfo)
	mock.lockApprovedUsers.Unlock()
	return mock.ApprovedUsersFunc()
}

// ApprovedUsersCalls gets all the calls that were made to ApprovedUsers.
// Check the length with:
//
//	len(mockedApprovedUsers.ApprovedUsersCalls())
func (mock *ApprovedUsersMock) ApprovedUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockApprovedUsers.RLock()
	calls = mock.calls.ApprovedUsers
	mock.lockApprovedUsers.RUnlock()
	return calls
}

// ResetApprovedUsersCalls reset all the calls that were made to ApprovedUsers.
func (mock *ApprovedUsersMock) ResetApprovedUsersCalls() {
	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = nil
	mock.lockApprovedUsers.Unlock()
}

// IsApprovedUser calls IsApprovedUserFunc.
func (mock *ApprovedUsersMock) IsApprovedUser(userID string) bool {
	if mock.IsApprovedUserFunc == nil {
		panic("ApprovedUsersMock.IsApprovedUserFunc: method is nil but ApprovedUsers.IsApprovedUser was just called")
	}
	callInfo := struct {
		UserID string
	}{
		UserID: userID,
	}
	mock.lockIsApprovedUser.Lock()
	mock.calls.IsApprovedUser = append(mock.calls.IsApprovedUser, callInfo)
	mock.lockIsApprovedUser.Unlock()
	return mock.IsApprovedUserFunc(userID)
}

// IsApprovedUserCalls gets all the calls that were made to IsApprovedUser.
// Check the length with:
//
//	len(mockedApprovedUsers.IsApprovedUserCalls())
func (mock *ApprovedUsersMock) IsApprovedUserCalls() []struct {
	UserID string
} {
	var calls []struct {
		UserID string
	}
	mock.lockIsApprovedUser.RLock()
	calls = mock.calls.IsApprovedUser
	mock.lockIsApprovedUser.RUnlock()
	return calls
}

// ResetIsApprovedUserCalls reset all the calls that were made to IsApprovedUser.
func (mock *ApprovedUsersMock) ResetIsApprovedUserCalls() {
	mock.lockIsApprovedUser.Lock()
	mock.calls.IsApprovedUser = nil
	mock.lockIsApprovedUser.Unlock()
}

// RemoveApprovedUser calls RemoveApprovedUserFunc.
func (mock *ApprovedUsersMock) RemoveApprovedUser(id string) error {
	if mock.RemoveApprovedUserFunc == nil {
		panic("ApprovedUsersMock.RemoveApprovedUserFunc: method is nil but ApprovedUsers.RemoveApprovedUser was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockRemoveApprovedUser.Lock()
	mock.calls.RemoveApprovedUser = append(mock.calls.RemoveApprovedUser, callInfo)
	mock.lockRemoveApprovedUser.Unlock()
	return mock.RemoveApprovedUserFunc(id)
}

// RemoveApprovedUserCalls gets all the calls that were made to RemoveApprovedUser.
// Check the length with:
//
//	len(mockedApprovedUsers.RemoveApprovedUserCalls())
func (mock *ApprovedUsersMock) RemoveApprovedUserCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockRemoveApprovedUser.RLock()
	calls = mock.calls.RemoveApprovedUser
	mock.lockRemoveApprovedUser.RUnlock()
	return calls
}

// ResetRemoveApprovedUserCalls reset all the calls that were made to RemoveApprovedUser.
func (mock *ApprovedUsersMock) ResetRemoveApprovedUserCalls() {
	mock.lockRemoveApprovedUser.Lock()
	mock.calls.RemoveApprovedUser = nil
	mock.lockRemoveApprovedUser.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ApprovedUsersMock) ResetCalls() {
	mock.lockAddApprovedUser.Lock()
	mock.calls.AddApprovedUser = nil
	mock.lockAddApprovedUser.Unlock()

	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = nil
	mock.lockApprovedUsers.Unlock()

	mock.lockIsApprovedUser.Lock()
	mock.calls.IsApprovedUser = nil
	mock.lockIsApprovedUser.Unlock()

	mock.lockRemoveApprovedUser.Lock()
	mock.calls.RemoveApprovedUser = nil
	mock.lockRemoveApprovedUser.Unlock()
}
