// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/redstone-md/shield/lib/spamcheck"
	"sync"
)

// MessageCheckerMock is a mock implementation of bot.MessageChecker.
//
//	func TestSomethingThatUsesMessageChecker(t *testing.T) {
//
//		// make and configure a mocked bot.MessageChecker
//		mockedMessageChecker := &MessageCheckerMock{
//			CheckFunc: func(request spamcheck.Request) (bool, []spamcheck.Response) {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedMessageChecker in code that requires bot.MessageChecker
//		// and then make assertions.
//
//	}
type MessageCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(request spamcheck.Request) (bool, []spamcheck.Response)

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// Request is the request argument value.
			Request spamcheck.Request
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *MessageCheckerMock) Check(request spamcheck.Request) (bool, []spamcheck.Response) {
	if mock.CheckFunc == nil {
		panic("MessageCheckerMock.CheckFunc: method is nil but MessageChecker.Check was just called")
	}
	callInfo := struct {
		Request spamcheck.Request
	}{
		Request: request,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(request)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedMessageChecker.CheckCalls())
func (mock *MessageCheckerMock) CheckCalls() []struct {
	Request spamcheck.Request
} {
	var calls []struct {
		Request spamcheck.Request
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}

// ResetCheckCalls reset all the calls that were made to Check.
func (mock *MessageCheckerMock) ResetCheckCalls() {
	mock.lockCheck.Lock()
	mock.calls.Check = nil
	mock.lockCheck.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MessageCheckerMock) ResetCalls() {
	mock.lockCheck.Lock()
	mock.calls.Check = nil
	mock.lockCheck.Unlock()
}
