// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SampleUpdaterMock is a mock implementation of bot.SampleUpdater.
//
//	func TestSomethingThatUsesSampleUpdater(t *testing.T) {
//
//		// make and configure a mocked bot.SampleUpdater
//		mockedSampleUpdater := &SampleUpdaterMock{
//			RemoveHamFunc: func(msg string) error {
//				panic("mock out the RemoveHam method")
//			},
//			RemoveSpamFunc: func(msg string) error {
//				panic("mock out the RemoveSpam method")
//			},
//			UpdateHamFunc: func(msg string) error {
//				panic("mock out the UpdateHam method")
//			},
//			UpdateSpamFunc: func(msg string) error {
//				panic("mock out the UpdateSpam method")
//			},
//		}
//
//		// use mockedSampleUpdater in code that requires bot.SampleUpdater
//		// and then make assertions.
//
//	}
type SampleUpdaterMock struct {
	// RemoveHamFunc mocks the RemoveHam method.
	RemoveHamFunc func(msg string) error

	// RemoveSpamFunc mocks the RemoveSpam method.
	RemoveSpamFunc func(msg string) error

	// UpdateHamFunc mocks the UpdateHam method.
	UpdateHamFunc func(msg string) error

	// UpdateSpamFunc mocks the UpdateSpam method.
	UpdateSpamFunc func(msg string) error

	// calls tracks calls to the methods.
	calls struct {
		// RemoveHam holds details about calls to the RemoveHam method.
		RemoveHam []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// RemoveSpam holds details about calls to the RemoveSpam method.
		RemoveSpam []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// UpdateHam holds details about calls to the UpdateHam method.
		UpdateHam []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// UpdateSpam holds details about calls to the UpdateSpam method.
		UpdateSpam []struct {
			// Msg is the msg argument value.
			Msg string
		}
	}
	lockRemoveHam  sync.RWMutex
	lockRemoveSpam sync.RWMutex
	lockUpdateHam  sync.RWMutex
	lockUpdateSpam sync.RWMutex
}

// RemoveHam calls RemoveHamFunc.
func (mock *SampleUpdaterMock) RemoveHam(msg string) error {
	if mock.RemoveHamFunc == nil {
		panic("SampleUpdaterMock.RemoveHamFunc: method is nil but SampleUpdater.RemoveHam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockRemoveHam.Lock()
	mock.calls.RemoveHam = append(mock.calls.RemoveHam, callInfo)
	mock.lockRemoveHam.Unlock()
	return mock.RemoveHamFunc(msg)
}

// RemoveHamCalls gets all the calls that were made to RemoveHam.
// Check the length with:
//
//	len(mockedSampleUpdater.RemoveHamCalls())
func (mock *SampleUpdaterMock) RemoveHamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockRemoveHam.RLock()
	calls = mock.calls.RemoveHam
	mock.lockRemoveHam.RUnlock()
	return calls
}

// ResetRemoveHamCalls reset all the calls that were made to RemoveHam.
func (mock *SampleUpdaterMock) ResetRemoveHamCalls() {
	mock.lockRemoveHam.Lock()
	mock.calls.RemoveHam = nil
	mock.lockRemoveHam.Unlock()
}

// RemoveSpam calls RemoveSpamFunc.
func (mock *SampleUpdaterMock) RemoveSpam(msg string) error {
	if mock.RemoveSpamFunc == nil {
		panic("SampleUpdaterMock.RemoveSpamFunc: method is nil but SampleUpdater.RemoveSpam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockRemoveSpam.Lock()
	mock.calls.RemoveSpam = append(mock.calls.RemoveSpam, callInfo)
	mock.lockRemoveSpam.Unlock()
	return mock.RemoveSpamFunc(msg)
}

// RemoveSpamCalls gets all the calls that were made to RemoveSpam.
// Check the length with:
//
//	len(mockedSampleUpdater.RemoveSpamCalls())
func (mock *SampleUpdaterMock) RemoveSpamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockRemoveSpam.RLock()
	calls = mock.calls.RemoveSpam
	mock.lockRemoveSpam.RUnlock()
	return calls
}

// ResetRemoveSpamCalls reset all the calls that were made to RemoveSpam.
func (mock *SampleUpdaterMock) ResetRemoveSpamCalls() {
	mock.lockRemoveSpam.Lock()
	mock.calls.RemoveSpam = nil
	mock.lockRemoveSpam.Unlock()
}

// UpdateHam calls UpdateHamFunc.
func (mock *SampleUpdaterMock) UpdateHam(msg string) error {
	if mock.UpdateHamFunc == nil {
		panic("SampleUpdaterMock.UpdateHamFunc: method is nil but SampleUpdater.UpdateHam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = append(mock.calls.UpdateHam, callInfo)
	mock.lockUpdateHam.Unlock()
	return mock.UpdateHamFunc(msg)
}

// UpdateHamCalls gets all the calls that were made to UpdateHam.
// Check the length with:
//
//	len(mockedSampleUpdater.UpdateHamCalls())
func (mock *SampleUpdaterMock) UpdateHamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockUpdateHam.RLock()
	calls = mock.calls.UpdateHam
	mock.lockUpdateHam.RUnlock()
	return calls
}

// ResetUpdateHamCalls reset all the calls that were made to UpdateHam.
func (mock *SampleUpdaterMock) ResetUpdateHamCalls() {
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()
}

// UpdateSpam calls UpdateSpamFunc.
func (mock *SampleUpdaterMock) UpdateSpam(msg string) error {
	if mock.UpdateSpamFunc == nil {
		panic("SampleUpdaterMock.UpdateSpamFunc: method is nil but SampleUpdater.UpdateSpam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = append(mock.calls.UpdateSpam, callInfo)
	mock.lockUpdateSpam.Unlock()
	return mock.UpdateSpamFunc(msg)
}

// UpdateSpamCalls gets all the calls that were made to UpdateSpam.
// Check the length with:
//
//	len(mockedSampleUpdater.UpdateSpamCalls())
func (mock *SampleUpdaterMock) UpdateSpamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockUpdateSpam.RLock()
	calls = mock.calls.UpdateSpam
	mock.lockUpdateSpam.RUnlock()
	return calls
}

// ResetUpdateSpamCalls reset all the calls that were made to UpdateSpam.
func (mock *SampleUpdaterMock) ResetUpdateSpamCalls() {
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *SampleUpdaterMock) ResetCalls() {
	mock.lockRemoveHam.Lock()
	mock.calls.RemoveHam = nil
	mock.lockRemoveHam.Unlock()

	mock.lockRemoveSpam.Lock()
	mock.calls.RemoveSpam = nil
	mock.lockRemoveSpam.Unlock()

	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()

	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}
