// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/redstone-md/shield/lib/tgspam"
	"io"
	"sync"
)

// SampleLoaderMock is a mock implementation of bot.SampleLoader.
//
//	func TestSomethingThatUsesSampleLoader(t *testing.T) {
//
//		// make and configure a mocked bot.SampleLoader
//		mockedSampleLoader := &SampleLoaderMock{
//			LoadSamplesFunc: func(exclReader io.Reader, spamReaders []io.Reader, hamReaders []io.Reader) (tgspam.LoadResult, error) {
//				panic("mock out the LoadSamples method")
//			},
//			LoadStopWordsFunc: func(readers ...io.Reader) (tgspam.LoadResult, error) {
//				panic("mock out the LoadStopWords method")
//			},
//		}
//
//		// use mockedSampleLoader in code that requires bot.SampleLoader
//		// and then make assertions.
//
//	}
type SampleLoaderMock struct {
	// LoadSamplesFunc mocks the LoadSamples method.
	LoadSamplesFunc func(exclReader io.Reader, spamReaders []io.Reader, hamReaders []io.Reader) (tgspam.LoadResult, error)

	// LoadStopWordsFunc mocks the LoadStopWords method.
	LoadStopWordsFunc func(readers ...io.Reader) (tgspam.LoadResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// LoadSamples holds details about calls to the LoadSamples method.
		LoadSamples []struct {
			// ExclReader is the exclReader argument value.
			ExclReader io.Reader
			// SpamReaders is the spamReaders argument value.
			SpamReaders []io.Reader
			// HamReaders is the hamReaders argument value.
			HamReaders []io.Reader
		}
		// LoadStopWords holds details about calls to the LoadStopWords method.
		LoadStopWords []struct {
			// Readers is the readers argument value.
			Readers []io.Reader
		}
	}
	lockLoadSamples   sync.RWMutex
	lockLoadStopWords sync.RWMutex
}

// LoadSamples calls LoadSamplesFunc.
func (mock *SampleLoaderMock) LoadSamples(exclReader io.Reader, spamReaders []io.Reader, hamReaders []io.Reader) (tgspam.LoadResult, error) {
	if mock.LoadSamplesFunc == nil {
		panic("SampleLoaderMock.LoadSamplesFunc: method is nil but SampleLoader.LoadSamples was just called")
	}
	callInfo := struct {
		ExclReader  io.Reader
		SpamReaders []io.Reader
		HamReaders  []io.Reader
	}{
		ExclReader:  exclReader,
		SpamReaders: spamReaders,
		HamReaders:  hamReaders,
	}
	mock.lockLoadSamples.Lock()
	mock.calls.LoadSamples = append(mock.calls.LoadSamples, callInfo)
	mock.lockLoadSamples.Unlock()
	return mock.LoadSamplesFunc(exclReader, spamReaders, hamReaders)
}

// LoadSamplesCalls gets all the calls that were made to LoadSamples.
// Check the length with:
//
//	len(mockedSampleLoader.LoadSamplesCalls())
func (mock *SampleLoaderMock) LoadSamplesCalls() []struct {
	ExclReader  io.Reader
	SpamReaders []io.Reader
	HamReaders  []io.Reader
} {
	var calls []struct {
		ExclReader  io.Reader
		SpamReaders []io.Reader
		HamReaders  []io.Reader
	}
	mock.lockLoadSamples.RLock()
	calls = mock.calls.LoadSamples
	mock.lockLoadSamples.RUnlock()
	return calls
}

// ResetLoadSamplesCalls reset all the calls that were made to LoadSamples.
func (mock *SampleLoaderMock) ResetLoadSamplesCalls() {
	mock.lockLoadSamples.Lock()
	mock.calls.LoadSamples = nil
	mock.lockLoadSamples.Unlock()
}

// LoadStopWords calls LoadStopWordsFunc.
func (mock *SampleLoaderMock) LoadStopWords(readers ...io.Reader) (tgspam.LoadResult, error) {
	if mock.LoadStopWordsFunc == nil {
		panic("SampleLoaderMock.LoadStopWordsFunc: method is nil but SampleLoader.LoadStopWords was just called")
	}
	callInfo := struct {
		Readers []io.Reader
	}{
		Readers: readers,
	}
	mock.lockLoadStopWords.Lock()
	mock.calls.LoadStopWords = append(mock.calls.LoadStopWords, callInfo)
	mock.lockLoadStopWords.Unlock()
	return mock.LoadStopWordsFunc(readers...)
}

// LoadStopWordsCalls gets all the calls that were made to LoadStopWords.
// Check the length with:
//
//	len(mockedSampleLoader.LoadStopWordsCalls())
func (mock *SampleLoaderMock) LoadStopWordsCalls() []struct {
	Readers []io.Reader
} {
	var calls []struct {
		Readers []io.Reader
	}
	mock.lockLoadStopWords.RLock()
	calls = mock.calls.LoadStopWords
	mock.lockLoadStopWords.RUnlock()
	return calls
}

// ResetLoadStopWordsCalls reset all the calls that were made to LoadStopWords.
func (mock *SampleLoaderMock) ResetLoadStopWordsCalls() {
	mock.lockLoadStopWords.Lock()
	mock.calls.LoadStopWords = nil
	mock.lockLoadStopWords.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *SampleLoaderMock) ResetCalls() {
	mock.lockLoadSamples.Lock()
	mock.calls.LoadSamples = nil
	mock.lockLoadSamples.Unlock()

	mock.lockLoadStopWords.Lock()
	mock.calls.LoadStopWords = nil
	mock.lockLoadStopWords.Unlock()
}
