// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/redstone-md/shield/app/storage"
	"sync"
)

// DetectedSpamMock is a mock implementation of webapi.DetectedSpam.
//
//	func TestSomethingThatUsesDetectedSpam(t *testing.T) {
//
//		// make and configure a mocked webapi.DetectedSpam
//		mockedDetectedSpam := &DetectedSpamMock{
//			FindByUserIDFunc: func(ctx context.Context, tenantID string, userID int64) (*storage.DetectedSpamInfo, error) {
//				panic("mock out the FindByUserID method")
//			},
//			ReadFunc: func(ctx context.Context, tenantID string) ([]storage.DetectedSpamInfo, error) {
//				panic("mock out the Read method")
//			},
//			SetAddedToSamplesFlagFunc: func(ctx context.Context, tenantID string, id int64) error {
//				panic("mock out the SetAddedToSamplesFlag method")
//			},
//		}
//
//		// use mockedDetectedSpam in code that requires webapi.DetectedSpam
//		// and then make assertions.
//
//	}
type DetectedSpamMock struct {
	// FindByUserIDFunc mocks the FindByUserID method.
	FindByUserIDFunc func(ctx context.Context, tenantID string, userID int64) (*storage.DetectedSpamInfo, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, tenantID string) ([]storage.DetectedSpamInfo, error)

	// SetAddedToSamplesFlagFunc mocks the SetAddedToSamplesFlag method.
	SetAddedToSamplesFlagFunc func(ctx context.Context, tenantID string, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// FindByUserID holds details about calls to the FindByUserID method.
		FindByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TenantID is the tenantID argument value.
			TenantID string
			// UserID is the userID argument value.
			UserID int64
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TenantID is the tenantID argument value.
			TenantID string
		}
		// SetAddedToSamplesFlag holds details about calls to the SetAddedToSamplesFlag method.
		SetAddedToSamplesFlag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TenantID is the tenantID argument value.
			TenantID string
			// ID is the id argument value.
			ID int64
		}
	}
	lockFindByUserID          sync.RWMutex
	lockRead                  sync.RWMutex
	lockSetAddedToSamplesFlag sync.RWMutex
}

// FindByUserID calls FindByUserIDFunc.
func (mock *DetectedSpamMock) FindByUserID(ctx context.Context, tenantID string, userID int64) (*storage.DetectedSpamInfo, error) {
	if mock.FindByUserIDFunc == nil {
		panic("DetectedSpamMock.FindByUserIDFunc: method is nil but DetectedSpam.FindByUserID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		TenantID string
		UserID   int64
	}{
		Ctx:      ctx,
		TenantID: tenantID,
		UserID:   userID,
	}
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = append(mock.calls.FindByUserID, callInfo)
	mock.lockFindByUserID.Unlock()
	return mock.FindByUserIDFunc(ctx, tenantID, userID)
}

// FindByUserIDCalls gets all the calls that were made to FindByUserID.
// Check the length with:
//
//	len(mockedDetectedSpam.FindByUserIDCalls())
func (mock *DetectedSpamMock) FindByUserIDCalls() []struct {
	Ctx      context.Context
	TenantID string
	UserID   int64
} {
	var calls []struct {
		Ctx      context.Context
		TenantID string
		UserID   int64
	}
	mock.lockFindByUserID.RLock()
	calls = mock.calls.FindByUserID
	mock.lockFindByUserID.RUnlock()
	return calls
}

// ResetFindByUserIDCalls reset all the calls that were made to FindByUserID.
func (mock *DetectedSpamMock) ResetFindByUserIDCalls() {
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = nil
	mock.lockFindByUserID.Unlock()
}

// Read calls ReadFunc.
func (mock *DetectedSpamMock) Read(ctx context.Context, tenantID string) ([]storage.DetectedSpamInfo, error) {
	if mock.ReadFunc == nil {
		panic("DetectedSpamMock.ReadFunc: method is nil but DetectedSpam.Read was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		TenantID string
	}{
		Ctx:      ctx,
		TenantID: tenantID,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, tenantID)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedDetectedSpam.ReadCalls())
func (mock *DetectedSpamMock) ReadCalls() []struct {
	Ctx      context.Context
	TenantID string
} {
	var calls []struct {
		Ctx      context.Context
		TenantID string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ResetReadCalls reset all the calls that were made to Read.
func (mock *DetectedSpamMock) ResetReadCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}

// SetAddedToSamplesFlag calls SetAddedToSamplesFlagFunc.
func (mock *DetectedSpamMock) SetAddedToSamplesFlag(ctx context.Context, tenantID string, id int64) error {
	if mock.SetAddedToSamplesFlagFunc == nil {
		panic("DetectedSpamMock.SetAddedToSamplesFlagFunc: method is nil but DetectedSpam.SetAddedToSamplesFlag was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		TenantID string
		ID       int64
	}{
		Ctx:      ctx,
		TenantID: tenantID,
		ID:       id,
	}
	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = append(mock.calls.SetAddedToSamplesFlag, callInfo)
	mock.lockSetAddedToSamplesFlag.Unlock()
	return mock.SetAddedToSamplesFlagFunc(ctx, tenantID, id)
}

// SetAddedToSamplesFlagCalls gets all the calls that were made to SetAddedToSamplesFlag.
// Check the length with:
//
//	len(mockedDetectedSpam.SetAddedToSamplesFlagCalls())
func (mock *DetectedSpamMock) SetAddedToSamplesFlagCalls() []struct {
	Ctx      context.Context
	TenantID string
	ID       int64
} {
	var calls []struct {
		Ctx      context.Context
		TenantID string
		ID       int64
	}
	mock.lockSetAddedToSamplesFlag.RLock()
	calls = mock.calls.SetAddedToSamplesFlag
	mock.lockSetAddedToSamplesFlag.RUnlock()
	return calls
}

// ResetSetAddedToSamplesFlagCalls reset all the calls that were made to SetAddedToSamplesFlag.
func (mock *DetectedSpamMock) ResetSetAddedToSamplesFlagCalls() {
	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = nil
	mock.lockSetAddedToSamplesFlag.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DetectedSpamMock) ResetCalls() {
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = nil
	mock.lockFindByUserID.Unlock()

	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()

	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = nil
	mock.lockSetAddedToSamplesFlag.Unlock()
}
