// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

type SpamFilterMock struct {
	DynamicSamplesFunc          func(ctx context.Context) ([]string, []string, error)
	ReloadSamplesFunc           func(ctx context.Context) error
	RemoveDynamicHamSampleFunc  func(sample string) error
	RemoveDynamicSpamSampleFunc func(sample string) error
	UpdateHamFunc               func(msg string) error
	UpdateSpamFunc              func(msg string) error

	calls struct {
		DynamicSamples          []struct{ Ctx context.Context }
		ReloadSamples           []struct{ Ctx context.Context }
		RemoveDynamicHamSample  []struct{ Sample string }
		RemoveDynamicSpamSample []struct{ Sample string }
		UpdateHam               []struct{ Msg string }
		UpdateSpam              []struct{ Msg string }
	}
	lockDynamicSamples          sync.RWMutex
	lockReloadSamples           sync.RWMutex
	lockRemoveDynamicHamSample  sync.RWMutex
	lockRemoveDynamicSpamSample sync.RWMutex
	lockUpdateHam               sync.RWMutex
	lockUpdateSpam              sync.RWMutex
}

func (mock *SpamFilterMock) DynamicSamples(ctx context.Context) ([]string, []string, error) {
	if mock.DynamicSamplesFunc == nil {
		panic("SpamFilterMock.DynamicSamplesFunc: method is nil but SpamFilter.DynamicSamples was just called")
	}
	callInfo := struct{ Ctx context.Context }{Ctx: ctx}
	mock.lockDynamicSamples.Lock()
	mock.calls.DynamicSamples = append(mock.calls.DynamicSamples, callInfo)
	mock.lockDynamicSamples.Unlock()
	return mock.DynamicSamplesFunc(ctx)
}

func (mock *SpamFilterMock) DynamicSamplesCalls() []struct{ Ctx context.Context } {
	var calls []struct{ Ctx context.Context }
	mock.lockDynamicSamples.RLock()
	calls = mock.calls.DynamicSamples
	mock.lockDynamicSamples.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetDynamicSamplesCalls() {
	mock.lockDynamicSamples.Lock()
	mock.calls.DynamicSamples = nil
	mock.lockDynamicSamples.Unlock()
}

func (mock *SpamFilterMock) ReloadSamples(ctx context.Context) error {
	if mock.ReloadSamplesFunc == nil {
		panic("SpamFilterMock.ReloadSamplesFunc: method is nil but SpamFilter.ReloadSamples was just called")
	}
	callInfo := struct{ Ctx context.Context }{Ctx: ctx}
	mock.lockReloadSamples.Lock()
	mock.calls.ReloadSamples = append(mock.calls.ReloadSamples, callInfo)
	mock.lockReloadSamples.Unlock()
	return mock.ReloadSamplesFunc(ctx)
}

func (mock *SpamFilterMock) ReloadSamplesCalls() []struct{ Ctx context.Context } {
	var calls []struct{ Ctx context.Context }
	mock.lockReloadSamples.RLock()
	calls = mock.calls.ReloadSamples
	mock.lockReloadSamples.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetReloadSamplesCalls() {
	mock.lockReloadSamples.Lock()
	mock.calls.ReloadSamples = nil
	mock.lockReloadSamples.Unlock()
}

func (mock *SpamFilterMock) RemoveDynamicHamSample(sample string) error {
	if mock.RemoveDynamicHamSampleFunc == nil {
		panic("SpamFilterMock.RemoveDynamicHamSampleFunc: method is nil but SpamFilter.RemoveDynamicHamSample was just called")
	}
	callInfo := struct{ Sample string }{Sample: sample}
	mock.lockRemoveDynamicHamSample.Lock()
	mock.calls.RemoveDynamicHamSample = append(mock.calls.RemoveDynamicHamSample, callInfo)
	mock.lockRemoveDynamicHamSample.Unlock()
	return mock.RemoveDynamicHamSampleFunc(sample)
}

func (mock *SpamFilterMock) RemoveDynamicHamSampleCalls() []struct{ Sample string } {
	var calls []struct{ Sample string }
	mock.lockRemoveDynamicHamSample.RLock()
	calls = mock.calls.RemoveDynamicHamSample
	mock.lockRemoveDynamicHamSample.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetRemoveDynamicHamSampleCalls() {
	mock.lockRemoveDynamicHamSample.Lock()
	mock.calls.RemoveDynamicHamSample = nil
	mock.lockRemoveDynamicHamSample.Unlock()
}

func (mock *SpamFilterMock) RemoveDynamicSpamSample(sample string) error {
	if mock.RemoveDynamicSpamSampleFunc == nil {
		panic("SpamFilterMock.RemoveDynamicSpamSampleFunc: method is nil but SpamFilter.RemoveDynamicSpamSample was just called")
	}
	callInfo := struct{ Sample string }{Sample: sample}
	mock.lockRemoveDynamicSpamSample.Lock()
	mock.calls.RemoveDynamicSpamSample = append(mock.calls.RemoveDynamicSpamSample, callInfo)
	mock.lockRemoveDynamicSpamSample.Unlock()
	return mock.RemoveDynamicSpamSampleFunc(sample)
}

func (mock *SpamFilterMock) RemoveDynamicSpamSampleCalls() []struct{ Sample string } {
	var calls []struct{ Sample string }
	mock.lockRemoveDynamicSpamSample.RLock()
	calls = mock.calls.RemoveDynamicSpamSample
	mock.lockRemoveDynamicSpamSample.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetRemoveDynamicSpamSampleCalls() {
	mock.lockRemoveDynamicSpamSample.Lock()
	mock.calls.RemoveDynamicSpamSample = nil
	mock.lockRemoveDynamicSpamSample.Unlock()
}

func (mock *SpamFilterMock) UpdateHam(msg string) error {
	if mock.UpdateHamFunc == nil {
		panic("SpamFilterMock.UpdateHamFunc: method is nil but SpamFilter.UpdateHam was just called")
	}
	callInfo := struct{ Msg string }{Msg: msg}
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = append(mock.calls.UpdateHam, callInfo)
	mock.lockUpdateHam.Unlock()
	return mock.UpdateHamFunc(msg)
}

func (mock *SpamFilterMock) UpdateHamCalls() []struct{ Msg string } {
	var calls []struct{ Msg string }
	mock.lockUpdateHam.RLock()
	calls = mock.calls.UpdateHam
	mock.lockUpdateHam.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetUpdateHamCalls() {
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()
}

func (mock *SpamFilterMock) UpdateSpam(msg string) error {
	if mock.UpdateSpamFunc == nil {
		panic("SpamFilterMock.UpdateSpamFunc: method is nil but SpamFilter.UpdateSpam was just called")
	}
	callInfo := struct{ Msg string }{Msg: msg}
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = append(mock.calls.UpdateSpam, callInfo)
	mock.lockUpdateSpam.Unlock()
	return mock.UpdateSpamFunc(msg)
}

func (mock *SpamFilterMock) UpdateSpamCalls() []struct{ Msg string } {
	var calls []struct{ Msg string }
	mock.lockUpdateSpam.RLock()
	calls = mock.calls.UpdateSpam
	mock.lockUpdateSpam.RUnlock()
	return calls
}

func (mock *SpamFilterMock) ResetUpdateSpamCalls() {
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}

func (mock *SpamFilterMock) ResetCalls() {
	mock.lockDynamicSamples.Lock()
	mock.calls.DynamicSamples = nil
	mock.lockDynamicSamples.Unlock()

	mock.lockReloadSamples.Lock()
	mock.calls.ReloadSamples = nil
	mock.lockReloadSamples.Unlock()

	mock.lockRemoveDynamicHamSample.Lock()
	mock.calls.RemoveDynamicHamSample = nil
	mock.lockRemoveDynamicHamSample.Unlock()

	mock.lockRemoveDynamicSpamSample.Lock()
	mock.calls.RemoveDynamicSpamSample = nil
	mock.lockRemoveDynamicSpamSample.Unlock()

	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()

	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}
